FROM gcc:latest

WORKDIR /workspace

RUN apt-get update && apt-get install -y \
    cmake \
    make \
    g++ \
    python3 \
    python3-pip \
    cppcheck \
    lcov \
    git \
    wget \
    curl \
    vim && \
    apt-get clean

RUN pip install conan gcovr --break-system-packages

RUN apt-get install -y ninja-build

# Print versions
RUN gcc --version && g++ --version && conan --version && cppcheck --version && gcovr --version
