FROM ubuntu:20.04

ENV DEBIAN_FRONTEND=noninteractive

RUN apt update && apt install -y \
    build-essential cmake qtbase5-dev qttools5-dev-tools \
    libgl1-mesa-dev libxkbcommon-x11-0 wget unzip patchelf lcov cmake make g++ cppcheck libfuse2

RUN wget https://github.com/probonopd/linuxdeployqt/releases/download/continuous/linuxdeployqt-continuous-x86_64.AppImage \
    && chmod +x linuxdeployqt-continuous-x86_64.AppImage \
    && mv linuxdeployqt-continuous-x86_64.AppImage /usr/local/bin/linuxdeployqt


