FROM ubuntu:22.04
   
RUN apt-get update && apt-get install -y \
    cmake \
    build-essential \
    make \
    gcc \
    g++ \
    gdb \
    python3 \
    python3-pip \
    cppcheck \
    lcov \
    git \
    wget \
    ninja-build \
    curl \
    can-utils \
    iproute2  \
    vim && \
    apt-get clean

RUN pip install conan gcovr python-can

RUN conan profile detect
